const roleDataArray = [
  { name: 'Alchemist', id: 1 },
  { name: 'Amnesiac', id: 2 },
  { name: 'Artist', id: 3 },
  { name: 'Atheist', id: 4 },
  { name: 'Balloonist', id: 5 },
  { name: 'Bounty Hunter', id: 6 },
  { name: 'Cannibal', id: 7 },
  { name: 'Chambermaid', id: 8 },
  { name: 'Chef', id: 9 },
  { name: 'Choirboy', id: 10 },
  { name: 'Clockmaker', id: 11 },
  { name: 'Courtier', id: 12 },
  { name: 'Cult Leader', id: 13 },
  { name: 'Dreamer', id: 14 },
  { name: 'Empath', id: 15 },
  { name: 'Engineer', id: 16 },
  { name: 'Exorcist', id: 17 },
  { name: 'Farmer', id: 18 },
  { name: 'Fisherman', id: 19 },
  { name: 'Flowergirl', id: 20 },
  { name: 'Fool', id: 21 },
  { name: 'Fortune Teller', id: 22 },
  { name: 'Gambler', id: 23 },
  { name: 'General', id: 24 },
  { name: 'Gossip', id: 25 },
  { name: 'Grandmother', id: 26 },
  { name: 'Huntsman', id: 27 },
  { name: 'Innkeeper', id: 28 },
  { name: 'Investigator', id: 29 },
  { name: 'Juggler', id: 30 },
  { name: 'King', id: 31 },
  { name: 'Knight', id: 32 },
  { name: 'Librarian', id: 33 },
  { name: 'Lycanthrope', id: 34 },
  { name: 'Magician', id: 35 },
  { name: 'Mathematician', id: 36 },
  { name: 'Mayor', id: 37 },
  { name: 'Minstrel', id: 38 },
  { name: 'Monk', id: 39 },
  { name: 'Nightwatchman', id: 40 },
  { name: 'Noble', id: 41 },
  { name: 'Oracle', id: 42 },
  { name: 'Pacifist', id: 43 },
  { name: 'Philosopher', id: 44 },
  { name: 'Pixie', id: 45 },
  { name: 'Poppy Grower', id: 46 },
  { name: 'Preacher', id: 47 },
  { name: 'Professor', id: 48 },
  { name: 'Ravenkeeper', id: 49 },
  { name: 'Sage', id: 50 },
  { name: 'Sailor', id: 51 },
  { name: 'Savant', id: 52 },
  { name: 'Seamstress', id: 53 },
  { name: 'Slayer', id: 54 },
  { name: 'Snake Charmer', id: 55 },
  { name: 'Soldier', id: 56 },
  { name: 'Steward', id: 57 },
  { name: 'Tea Lady', id: 58 },
  { name: 'Town Crier', id: 59 },
  { name: 'Undertaker', id: 60 },
  { name: 'Virgin', id: 61 },
  { name: 'Washerwoman', id: 62 },
  { name: 'Acrobat', id: 63 },
  { name: 'Barber', id: 64 },
  { name: 'Butler', id: 65 },
  { name: 'Damsel', id: 66 },
  { name: 'Drunk', id: 67 },
  { name: 'Golem', id: 68 },
  { name: 'Goon', id: 69 },
  { name: 'Heretic', id: 70 },
  { name: 'Klutz', id: 71 },
  { name: 'Lunatic', id: 72 },
  { name: 'Moonchild', id: 73 },
  { name: 'Mutant', id: 74 },
  { name: 'Politician', id: 75 },
  { name: 'Puzzlemaster', id: 76 },
  { name: 'Recluse', id: 77 },
  { name: 'Saint', id: 78 },
  { name: 'Snitch', id: 79 },
  { name: 'Sweetheart', id: 80 },
  { name: 'Tinker', id: 81 },
  { name: 'Assassin', id: 82 },
  { name: 'Baron', id: 83 },
  { name: 'Boomdandy', id: 84 },
  { name: 'Cerenovus', id: 85 },
  { name: "Devil's Advocate", id: 86 },
  { name: 'Evil Twin', id: 87 },
  { name: 'Fearmonger', id: 88 },
  { name: 'Goblin', id: 89 },
  { name: 'Godfather', id: 90 },
  { name: 'Marionette', id: 91 },
  { name: 'Mastermind', id: 92 },
  { name: 'Mezepheles', id: 93 },
  { name: 'Organ Grinder', id: 94 },
  { name: 'Pit Hag', id: 95 },
  { name: 'Poisoner', id: 96 },
  { name: 'Psychopath', id: 97 },
  { name: 'Scarlet Woman', id: 98 },
  { name: 'Spy', id: 99 },
  { name: 'Vizier', id: 100 },
  { name: 'Widow', id: 101 },
  { name: 'Witch', id: 102 },
  { name: 'Al-Hadikhia', id: 103 },
  { name: 'Fang Gu', id: 104 },
  { name: 'Imp', id: 105 },
  { name: 'Legion', id: 106 },
  { name: 'Leviathan', id: 107 },
  { name: 'Lleech', id: 108 },
  { name: 'No Dashii', id: 109 },
  { name: 'Po', id: 110 },
  { name: 'Pukka', id: 111 },
  { name: 'Riot', id: 112 },
  { name: 'Shabaloth', id: 113 },
  { name: 'Vigormortis', id: 114 },
  { name: 'Vortox', id: 115 },
  { name: 'Zombuul', id: 116 },
  { name: 'Apprentice', id: 117 },
  { name: 'Barista', id: 118 },
  { name: 'Beggar', id: 119 },
  { name: 'Bishop', id: 120 },
  { name: 'Bone Collector', id: 121 },
  { name: 'Bureaucrat', id: 122 },
  { name: 'Butcher', id: 123 },
  { name: 'Deviant', id: 124 },
  { name: 'Gangster', id: 125 },
  { name: 'Gunslinger', id: 126 },
  { name: 'Harlot', id: 127 },
  { name: 'Judge', id: 128 },
  { name: 'Matron', id: 129 },
  { name: 'Scapegoat', id: 130 },
  { name: 'Thief', id: 131 },
  { name: 'Voudon', id: 132 },
  { name: 'High Priestess', id: 133 },
  { name: 'Harpy', id: 134 },
  { name: 'Plague Doctor', id: 135 }, 
  { name: 'Shugenja', id: 136 }, 
  { name: 'Ojo', id: 137 }
]

export default roleDataArray