INSERT INTO types (name)
VALUES ('Townsfolk'),
       ('Outsider'),
       ('Minion'),
       ('Demon'),
       ('Traveller');

INSERT INTO roles(name, type_id)
VALUES ('Alchemist', 1),
       ('Amnesiac', 1),
       ('Artist', 1),
       ('Atheist', 1),
       ('Balloonist', 1),
       ('Bounty Hunter', 1),
       ('Cannibal', 1),
       ('Chambermaid', 1),
       ('Chef', 1),
       ('Choirboy', 1),
       ('Clockmaker', 1),
       ('Courtier', 1),
       ('Cult Leader', 1),
       ('Dreamer', 1),
       ('Empath', 1),
       ('Engineer', 1),
       ('Exorcist', 1),
       ('Farmer', 1),
       ('Fisherman', 1),
       ('Flowergirl', 1),
       ('Fool', 1),
       ('Fortune Teller', 1),
       ('Gambler', 1),
       ('General', 1),
       ('Gossip', 1),
       ('Grandmother', 1),
       ('Huntsman', 1),
       ('Innkeeper', 1),
       ('Investigator', 1),
       ('Juggler', 1),
       ('King', 1),
       ('Knight', 1),
       ('Librarian', 1),
       ('Lycanthrope', 1),
       ('Magician', 1),
       ('Mathematician', 1),
       ('Mayor', 1),
       ('Minstrel', 1),
       ('Monk', 1),
       ('Nightwatchman', 1),
       ('Noble', 1),
       ('Oracle', 1),
       ('Pacifist', 1),
       ('Philosopher', 1),
       ('Pixie', 1),
       ('Poppy Grower', 1),
       ('Preacher', 1),
       ('Professor', 1),
       ('Ravenkeeper', 1),
       ('Sage', 1),
       ('Sailor', 1),
       ('Savant', 1),
       ('Seamstress', 1),
       ('Slayer', 1),
       ('Snake Charmer', 1),
       ('Soldier', 1),
       ('Steward', 1),
       ('Tea Lady', 1),
       ('Town Crier', 1),
       ('Undertaker', 1),
       ('Virgin', 1),
       ('Washerwoman', 1),
       ('Acrobat', 2),
       ('Barber', 2),
       ('Butler', 2),
       ('Damsel', 2),
       ('Drunk', 2),
       ('Golem', 2),
       ('Goon', 2),
       ('Heretic', 2),
       ('Klutz', 2),
       ('Lunatic', 2),
       ('Moonchild', 2),
       ('Mutant', 2),
       ('Politician', 2),
       ('Puzzlemaster', 2),
       ('Recluse', 2),
       ('Saint', 2),
       ('Snitch', 2),
       ('Sweetheart', 2),
       ('Tinker', 2),
       ('Assassin', 3),
       ('Baron', 3),
       ('Boomdandy', 3),
       ('Cerenovus', 3),
       ('Devil''s Advocate', 3),
       ('Evil Twin', 3),
       ('Fearmonger', 3),
       ('Goblin', 3),
       ('Godfather', 3),
       ('Marionette', 3),
       ('Mastermind', 3),
       ('Mezepheles', 3),
       ('Organ Grinder', 3),
       ('Pit Hag', 3),
       ('Poisoner', 3),
       ('Psychopath', 3),
       ('Scarlet Woman', 3),
       ('Spy', 3),
       ('Vizier', 3),
       ('Widow', 3),
       ('Witch', 3),
       ('Al-Hadikhia', 4),
       ('Fang Gu', 4),
       ('Imp', 4),
       ('Legion', 4),
       ('Leviathan', 4),
       ('Lleech', 4),
       ('No Dashii', 4),
       ('Po', 4),
       ('Pukka', 4),
       ('Riot', 4),
       ('Shabaloth', 4),
       ('Vigormortis', 4),
       ('Vortox', 4),
       ('Zombuul', 4),
       ('Apprentice', 5),
       ('Barista', 5),
       ('Beggar', 5),
       ('Bishop', 5),
       ('Bone Collector', 5),
       ('Bureaucrat', 5),
       ('Butcher', 5),
       ('Deviant', 5),
       ('Gangster', 5),
       ('Gunslinger', 5),
       ('Harlot', 5),
       ('Judge', 5),
       ('Matron', 5),
       ('Scapegoat', 5),
       ('Thief', 5),
       ('Voudon', 5)
       ('High Priestess', 1);
       
INSERT INTO games(date, game_won, is_evil, comments, starting_role_id, final_role_id)
VALUES ('2023-02-06', true, false, 'test', 1, 1),
       ('2023-02-06', false, false, 'test', 1, 1),
       ('2023-02-06', true, false, 'test', 4, 4),
       ('2023-02-06', true, false, 'test', 4, 4),
       ('2023-02-06', true, false, 'test', 4, 4),
       ('2023-02-06', false, false, 'test', 20, 20),
       ('2023-02-06', true, true, 'test', 80, 80);
